spring:
  datasource:
    url: jdbc:h2:mem:users
    username: sa
    password: password
    driverClassName: org.h2.Driver
  flyway:
    enabled: true
    locations: "classpath:migrate"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

logging:
  config: classpath:logback/logback-spring.xml

env:
  webauthn:
    rp-id: localhost
    origins:
      - http://localhost:3000
      - http://localhost:3001
    name: "WebAuthn Demo"
