CREATE TABLE registration_challenge
(
    id         MEDIUMINT    NOT NULL AUTO_INCREMENT,
    user_id    VARCHAR(255) PRIMARY KEY,
    challenge  VARCHAR(255) NOT NULL,
    expired_at DATETIME     NOT NULL
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);